version: "3"

services:
    api:
        container_name: api
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        restart: unless-stopped
        networks:
            - oehealth
        depends_on:
            - db
            - redis
        volumes:
            - oehealth-media:/app/media
            - oehealth-static:/app/static
        command: python manage.py runserver 0.0.0.0:8000
        env_file: env_dev
        environment:
            - FRONTEND_URL=http://localhost:3000/
            - STATIC_URL=${STATIC_URL}

    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: ./website/Dockerfile
        restart: unless-stopped
        env_file: env_dev
        networks:
            - oehealth
        command: yarn start

    db:
        container_name: db
        image: postgres:11-alpine
        ports:
            - 5432:5432
        restart: unless-stopped
        networks:
            - oehealth
        volumes:
            - oehealth-db:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=ohealth
            - POSTGRES_PASSWORD=ohealth
            - POSTGRES_DB=ohealth

    worker:
        container_name: worker
        build:
            context: ./backend
            dockerfile: ./Dockerfile
            args:
                STATIC_URL: "/static/"
        command: celery -A backend --app=backend.celery:app worker --loglevel=info
        restart: unless-stopped
        networks:
            - oehealth
        env_file: env_dev
        depends_on:
            - redis
            - mailhog
        volumes:
            - ./oehealth/templates/:/app/templates:Z,cached
            # shared volume between worker and api for media
            - oehealth-media:/app/media
            - oehealth-static:/app/static

    redis:
        container_name: redis
        image: redis:alpine
        command: redis-server --requirepass 4f6bbbb3eb3fdda88990143e
        env_file: env_dev
        ports:
            - 6379:6379
        restart: unless-stopped
        networks:
            - oehealth
        volumes:
            - oehealth-redis:/data

    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025 # smtp server
            - 8025:8025 # web ui. Visit http://localhost:8025/ to check emails
        restart: unless-stopped
        networks:
            - oehealth

    odoo:
        image: odoo:15.0
        depends_on:
            - odoodb
        ports:
            - 8069:8069
            - 8072:8072
        restart: unless-stopped
        volumes:
            - oehealth-odoo:/var/lib/odoo
            - ./config:/etc/odoo
            - ./addons:/mnt/extra-addons
        environment:
            - HOST=odoodb
            - USER=odoo
            - PASSWORD=odoo
            - PROXY_MODE=true
        networks:
            - oehealth
    odoodb:
        image: postgres:13
        restart: unless-stopped
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - oehealth-odoodb:/var/lib/postgresql/data/pgdata
        networks:
            - oehealth

    nginx:
        container_name: nginx
        image: nginx:latest
        volumes:
            - ./nginx/templates:/etc/nginx/templates
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - web-root1:/var/www/oehealth
            - web-root2:/var/www/oehealth-api
            - web-root3:/var/www/odoo
            - oehealth-media:/var/www/media
            - oehealth-static:/var/www/static
        networks:
            - oehealth
        ports:
            - 443:443
        depends_on:
            - nginx_cert
            - api
            - frontend
            - odoo
        environment:
            - NGINX_HOST=oehealth.devxhub.com
            - API_HOST=oehealth-api.devxhub.com
            - ODOO_HOST=admin.devxhub.com

    nginx_cert:
        container_name: nginx_cert
        image: nginx:latest
        volumes:
            - ./nginx/templates_http:/etc/nginx/templates
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - web-root1:/var/www/oehealth
            - web-root2:/var/www/oehealth-api
            - web-root3:/var/www/odoo
            - oehealth-media:/var/www/media
            - oehealth-static:/var/www/static
        networks:
            - oehealth
        ports:
            - 80:80
        depends_on:
            - api
            - frontend
            - odoo
        environment:
            - NGINX_HOST=oehealth.devxhub.com
            - API_HOST=oehealth-api.devxhub.com
            - ODOO_HOST=admin.devxhub.com

    certbot1:
        image: certbot/certbot
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - web-root1:/var/www/oehealth
            - web-root2:/var/www/oehealth-api
            - web-root3:/var/www/odoo
        depends_on:
            - nginx_cert
        command: certonly --webroot --email eliyas.devxhub@gmail.com --agree-tos --no-eff-email -n -w /var/www/oehealth --cert-name oehealth.devxhub.com -d oehealth.devxhub.com
    certbot2:
        image: certbot/certbot
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - web-root1:/var/www/oehealth
            - web-root2:/var/www/oehealth-api
            - web-root3:/var/www/odoo
        depends_on:
            - nginx_cert
        command: certonly --webroot --email eliyas.devxhub@gmail.com --agree-tos --no-eff-email -n -w /var/www/oehealth-api --cert-name oehealth-api.devxhub.com -d oehealth-api.devxhub.com
    certbot3:
        image: certbot/certbot
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - web-root1:/var/www/oehealth
            - web-root2:/var/www/oehealth-api
            - web-root3:/var/www/odoo
        depends_on:
            - nginx_cert
        command: certonly --webroot --email eliyas.devxhub@gmail.com --agree-tos --no-eff-email -n -w /var/www/odoo --cert-name admin.devxhub.com -d admin.devxhub.com

volumes:
    oehealth-media:
        driver: local
    oehealth-static:
        driver: local
    oehealth-db:
        driver: local
    oehealth-redis:
        driver: local
    certbot-etc:
        driver: local
    certbot-var:
        driver: local
    web-root:
        driver: local
    web-root1:
        driver: local
    web-root2:
        driver: local
    web-root3:
        driver: local
    oehealth-odoo:
        driver: local
    oehealth-odoodb:
        driver: local

networks:
    oehealth:
        driver: bridge
