---
- include_tasks: install_additional_packages.yml
  tags: packages

- include_tasks: setup_virtualenv.yml
  tags: virtualenv

- include_tasks: setup_django_app.yml
  tags: deploy

- include_tasks: setup_supervisor.yml
  tags: supervisor
